"""add company_name to qualification

Revision ID: 05416cf85289
Revises: e8b181a3aacf
Create Date: 2026-07-20 14:48:03.243091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05416cf85289'
down_revision: Union[str, Sequence[str], None] = 'e8b181a3aacf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_qualifications', sa.Column('company_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_qualifications', 'company_name')
    # ### end Alembic commands ###
