"""refactor timeline schema

Revision ID: 212fa3675a02
Revises: 30e39b8c25a9
Create Date: 2026-07-17 13:57:12.481898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212fa3675a02'
down_revision: Union[str, Sequence[str], None] = '30e39b8c25a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline_metadata', sa.Column('tender_segment', sa.String(length=255), nullable=True, comment='标段/包件名称'))
    op.add_column('timeline_metadata', sa.Column('acquisition_info', sa.JSON(), nullable=True, comment='招标文件领购渠道'))
    op.add_column('timeline_metadata', sa.Column('contacts', sa.JSON(), nullable=True, comment='联系人明细'))
    op.add_column('timeline_metadata', sa.Column('bid_validity_days', sa.Integer(), nullable=True, comment='投标有效期天数'))
    op.add_column('timeline_metadata', sa.Column('tender_milestones', sa.JSON(), nullable=True, comment='关键节点明细列表'))
    op.add_column('timeline_metadata', sa.Column('document_requirements', sa.JSON(), nullable=True, comment='标书装订要求'))
    op.add_column('timeline_metadata', sa.Column('construction_period_description', sa.Text(), nullable=True, comment='工期描述原文'))
    op.alter_column('timeline_metadata', 'project_id_code',
               existing_type=sa.VARCHAR(length=255),
               comment='项目编号/招标编号',
               existing_comment='项目唯一标识编号',
               existing_nullable=True)
    op.drop_column('timeline_metadata', 'construction_period_days')
    op.add_column('timeline_metadata', sa.Column('construction_period_days', sa.Integer(), nullable=True, comment='工期天数'))
    op.drop_column('timeline_metadata', 'document_copies')
    op.drop_column('timeline_metadata', 'qa_deadline')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline_metadata', sa.Column('qa_deadline', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='答疑死线'))
    op.add_column('timeline_metadata', sa.Column('document_copies', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='标书制作份数'))
    op.drop_column('timeline_metadata', 'construction_period_days')
    op.add_column('timeline_metadata', sa.Column('construction_period_days', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='工期要求'))
    op.alter_column('timeline_metadata', 'project_id_code',
               existing_type=sa.VARCHAR(length=255),
               comment='项目唯一标识编号',
               existing_comment='项目编号/招标编号',
               existing_nullable=True)
    op.drop_column('timeline_metadata', 'construction_period_description')
    op.drop_column('timeline_metadata', 'document_requirements')
    op.drop_column('timeline_metadata', 'tender_milestones')
    op.drop_column('timeline_metadata', 'bid_validity_days')
    op.drop_column('timeline_metadata', 'contacts')
    op.drop_column('timeline_metadata', 'acquisition_info')
    op.drop_column('timeline_metadata', 'tender_segment')
    # ### end Alembic commands ###
