"""refactor financial schema

Revision ID: 30e39b8c25a9
Revises: c12fdc2e6d09
Create Date: 2026-07-17 13:11:47.509654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30e39b8c25a9'
down_revision: Union[str, Sequence[str], None] = 'c12fdc2e6d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_metadata', sa.Column('sub_package_budgets', sa.JSON(), nullable=True, comment='分包预算明细'))
    op.add_column('financial_metadata', sa.Column('unit_price_limits', sa.JSON(), nullable=True, comment='单价控制价'))
    op.add_column('financial_metadata', sa.Column('provisional_sum', sa.JSON(), nullable=True, comment='暂列金额'))
    op.add_column('financial_metadata', sa.Column('contract_price_type', sa.String(length=255), nullable=True, comment='计价方式'))
    op.add_column('financial_metadata', sa.Column('tax_rate_requirement', sa.String(length=255), nullable=True, comment='税率要求'))
    op.add_column('financial_metadata', sa.Column('bid_bond', sa.JSON(), nullable=True, comment='投标保证金'))
    op.add_column('financial_metadata', sa.Column('performance_bond', sa.JSON(), nullable=True, comment='履约保证金'))
    op.add_column('financial_metadata', sa.Column('warranty_bond', sa.JSON(), nullable=True, comment='质保金'))
    op.add_column('financial_metadata', sa.Column('advance_payment_ratio', sa.Float(), nullable=True, comment='预付款比例'))
    op.add_column('financial_metadata', sa.Column('price_adjustment_clause', sa.Text(), nullable=True, comment='调价机制'))
    op.add_column('financial_metadata', sa.Column('delayed_payment_penalty', sa.Text(), nullable=True, comment='违约金条款'))
    op.drop_column('financial_metadata', 'budget')
    op.drop_column('financial_metadata', 'max_price_limit')
    op.add_column('financial_metadata', sa.Column('budget', sa.JSON(), nullable=True, comment='总预算'))
    op.add_column('financial_metadata', sa.Column('max_price_limit', sa.JSON(), nullable=True, comment='最高限价'))
    op.alter_column('financial_metadata', 'payment_milestones',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='付款节点',
               existing_comment='付款节点与结付比例',
               existing_nullable=True)
    op.drop_column('financial_metadata', 'bid_bond_ratio')
    op.drop_column('financial_metadata', 'performance_bond_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_metadata', sa.Column('performance_bond_ratio', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='履约保证金比例'))
    op.add_column('financial_metadata', sa.Column('bid_bond_ratio', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='投标保证金比例'))
    op.alter_column('financial_metadata', 'payment_milestones',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='付款节点与结付比例',
               existing_comment='付款节点',
               existing_nullable=True)
    op.alter_column('financial_metadata', 'max_price_limit',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_comment='最高限价',
               existing_nullable=True)
    op.alter_column('financial_metadata', 'budget',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               comment='预算',
               existing_comment='总预算',
               existing_nullable=True)
    op.drop_column('financial_metadata', 'delayed_payment_penalty')
    op.drop_column('financial_metadata', 'price_adjustment_clause')
    op.drop_column('financial_metadata', 'advance_payment_ratio')
    op.drop_column('financial_metadata', 'warranty_bond')
    op.drop_column('financial_metadata', 'performance_bond')
    op.drop_column('financial_metadata', 'bid_bond')
    op.drop_column('financial_metadata', 'tax_rate_requirement')
    op.drop_column('financial_metadata', 'contract_price_type')
    op.drop_column('financial_metadata', 'provisional_sum')
    op.drop_column('financial_metadata', 'unit_price_limits')
    op.drop_column('financial_metadata', 'sub_package_budgets')
    # ### end Alembic commands ###
