"""add user_id to TenantBase

Revision ID: 87e7cf35c010
Revises: be620d74a481
Create Date: 2026-07-21 10:27:12.710509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e7cf35c010'
down_revision: Union[str, Sequence[str], None] = 'be620d74a481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_audit_logs', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_agent_audit_logs_user_id'), 'agent_audit_logs', ['user_id'], unique=False)
    op.add_column('company_qualifications', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_company_qualifications_user_id'), 'company_qualifications', ['user_id'], unique=False)
    op.add_column('cost_estimates', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_cost_estimates_user_id'), 'cost_estimates', ['user_id'], unique=False)
    op.add_column('doc_chunks', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_doc_chunks_user_id'), 'doc_chunks', ['user_id'], unique=False)
    op.add_column('documents', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.add_column('engineering_metadata', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_engineering_metadata_user_id'), 'engineering_metadata', ['user_id'], unique=False)
    op.add_column('evaluation_metadata', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_evaluation_metadata_user_id'), 'evaluation_metadata', ['user_id'], unique=False)
    op.add_column('financial_metadata', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_financial_metadata_user_id'), 'financial_metadata', ['user_id'], unique=False)
    op.add_column('market_price_references', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_market_price_references_user_id'), 'market_price_references', ['user_id'], unique=False)
    op.add_column('projects', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.add_column('qualification_matches', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_qualification_matches_user_id'), 'qualification_matches', ['user_id'], unique=False)
    op.add_column('qualification_metadata', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_qualification_metadata_user_id'), 'qualification_metadata', ['user_id'], unique=False)
    op.add_column('risk_items', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_risk_items_user_id'), 'risk_items', ['user_id'], unique=False)
    op.add_column('timeline_metadata', sa.Column('user_id', sa.String(length=36), nullable=True, comment='数据创建者用户ID'))
    op.create_index(op.f('ix_timeline_metadata_user_id'), 'timeline_metadata', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_metadata_user_id'), table_name='timeline_metadata')
    op.drop_column('timeline_metadata', 'user_id')
    op.drop_index(op.f('ix_risk_items_user_id'), table_name='risk_items')
    op.drop_column('risk_items', 'user_id')
    op.drop_index(op.f('ix_qualification_metadata_user_id'), table_name='qualification_metadata')
    op.drop_column('qualification_metadata', 'user_id')
    op.drop_index(op.f('ix_qualification_matches_user_id'), table_name='qualification_matches')
    op.drop_column('qualification_matches', 'user_id')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_column('projects', 'user_id')
    op.drop_index(op.f('ix_market_price_references_user_id'), table_name='market_price_references')
    op.drop_column('market_price_references', 'user_id')
    op.drop_index(op.f('ix_financial_metadata_user_id'), table_name='financial_metadata')
    op.drop_column('financial_metadata', 'user_id')
    op.drop_index(op.f('ix_evaluation_metadata_user_id'), table_name='evaluation_metadata')
    op.drop_column('evaluation_metadata', 'user_id')
    op.drop_index(op.f('ix_engineering_metadata_user_id'), table_name='engineering_metadata')
    op.drop_column('engineering_metadata', 'user_id')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_column('documents', 'user_id')
    op.drop_index(op.f('ix_doc_chunks_user_id'), table_name='doc_chunks')
    op.drop_column('doc_chunks', 'user_id')
    op.drop_index(op.f('ix_cost_estimates_user_id'), table_name='cost_estimates')
    op.drop_column('cost_estimates', 'user_id')
    op.drop_index(op.f('ix_company_qualifications_user_id'), table_name='company_qualifications')
    op.drop_column('company_qualifications', 'user_id')
    op.drop_index(op.f('ix_agent_audit_logs_user_id'), table_name='agent_audit_logs')
    op.drop_column('agent_audit_logs', 'user_id')
    # ### end Alembic commands ###
