"""add parsed_metadata to document

Revision ID: 9673969f771b
Revises: de28c575af0a
Create Date: 2026-07-13 09:42:01.687728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9673969f771b'
down_revision: Union[str, Sequence[str], None] = 'de28c575af0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parsed_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'parsed_metadata')
    # ### end Alembic commands ###
