"""add pgvector and chunk metadata

Revision ID: 9cb01978bcd4
Revises: 5818c6ac52f2
Create Date: 2026-07-10 13:38:55.852572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9cb01978bcd4'
down_revision: Union[str, Sequence[str], None] = '5818c6ac52f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_chunks', sa.Column('section_title', sa.String(length=255), nullable=True))
    op.add_column('doc_chunks', sa.Column('content_type', sa.String(length=50), nullable=True))
    op.add_column('doc_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_chunks', 'embedding')
    op.drop_column('doc_chunks', 'content_type')
    op.drop_column('doc_chunks', 'section_title')
    # ### end Alembic commands ###
