"""refactor engineering schema

Revision ID: acebf2b5a5cc
Revises: 212fa3675a02
Create Date: 2026-07-17 14:14:59.103556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acebf2b5a5cc'
down_revision: Union[str, Sequence[str], None] = '212fa3675a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engineering_metadata', sa.Column('main_equipment_list', sa.JSON(), nullable=True, comment='主要设备及材料清单'))
    op.add_column('engineering_metadata', sa.Column('site_environment_constraints', sa.Text(), nullable=True, comment='现场环境与施工限制说明'))
    op.add_column('engineering_metadata', sa.Column('mandatory_standards', sa.JSON(), nullable=True, comment='强制性技术标准'))
    op.add_column('engineering_metadata', sa.Column('tech_validation', sa.JSON(), nullable=True, comment='样品及POC演示要求'))
    op.add_column('engineering_metadata', sa.Column('safety_and_env_requirements', sa.JSON(), nullable=True, comment='安全生产与文明施工要求'))
    op.alter_column('engineering_metadata', 'special_working_conditions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='特殊/恶劣实施工况',
               existing_comment='特殊/高难工况说明',
               existing_nullable=True)
    op.drop_column('engineering_metadata', 'main_equipment_quantities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engineering_metadata', sa.Column('main_equipment_quantities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='主要标的物定量配置'))
    op.alter_column('engineering_metadata', 'special_working_conditions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='特殊/高难工况说明',
               existing_comment='特殊/恶劣实施工况',
               existing_nullable=True)
    op.drop_column('engineering_metadata', 'safety_and_env_requirements')
    op.drop_column('engineering_metadata', 'tech_validation')
    op.drop_column('engineering_metadata', 'mandatory_standards')
    op.drop_column('engineering_metadata', 'site_environment_constraints')
    op.drop_column('engineering_metadata', 'main_equipment_list')
    # ### end Alembic commands ###
