"""refactor qualification schema

Revision ID: c12fdc2e6d09
Revises: 90a4fe56b9b2
Create Date: 2026-07-17 10:59:13.158338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c12fdc2e6d09'
down_revision: Union[str, Sequence[str], None] = '90a4fe56b9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualification_metadata', sa.Column('min_registered_capital_wuyuan', sa.Float(), nullable=True, comment='最低注册资本要求（万元）'))
    op.add_column('qualification_metadata', sa.Column('credit_and_legal_reqs', sa.JSON(), nullable=True, comment='信用与合规要求'))
    op.add_column('qualification_metadata', sa.Column('mandatory_qualifications', sa.JSON(), nullable=True, comment='强制性企业资质门槛'))
    op.add_column('qualification_metadata', sa.Column('system_certifications', sa.JSON(), nullable=True, comment='体系认证/特种许可'))
    op.add_column('qualification_metadata', sa.Column('personnel_requirements', sa.JSON(), nullable=True, comment='核心人员要求明细'))
    op.add_column('qualification_metadata', sa.Column('performance_requirements', sa.JSON(), nullable=True, comment='历史同类业绩门槛'))
    op.add_column('qualification_metadata', sa.Column('bonus_qualifications', sa.JSON(), nullable=True, comment='资质/业绩/人员加分项'))
    op.drop_column('qualification_metadata', 'special_licenses')
    op.drop_column('qualification_metadata', 'industry_qualifications')
    op.drop_column('qualification_metadata', 'core_personnel_certs')
    op.drop_column('qualification_metadata', 'historical_performance_reqs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualification_metadata', sa.Column('historical_performance_reqs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='历史业绩门槛'))
    op.add_column('qualification_metadata', sa.Column('core_personnel_certs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='核心人员证书'))
    op.add_column('qualification_metadata', sa.Column('industry_qualifications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='特定行业资质'))
    op.add_column('qualification_metadata', sa.Column('special_licenses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='特种许可证'))
    op.drop_column('qualification_metadata', 'bonus_qualifications')
    op.drop_column('qualification_metadata', 'performance_requirements')
    op.drop_column('qualification_metadata', 'personnel_requirements')
    op.drop_column('qualification_metadata', 'system_certifications')
    op.drop_column('qualification_metadata', 'mandatory_qualifications')
    op.drop_column('qualification_metadata', 'credit_and_legal_reqs')
    op.drop_column('qualification_metadata', 'min_registered_capital_wuyuan')
    # ### end Alembic commands ###
