"""add trace_info to docchunk

Revision ID: de28c575af0a
Revises: 9cb01978bcd4
Create Date: 2026-07-13 09:26:43.324225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de28c575af0a'
down_revision: Union[str, Sequence[str], None] = '9cb01978bcd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_chunks', sa.Column('trace_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_chunks', 'trace_info')
    # ### end Alembic commands ###
