"""add_invalid_bid_clauses

Revision ID: e8b181a3aacf
Revises: acebf2b5a5cc
Create Date: 2026-07-20 11:22:54.693022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b181a3aacf'
down_revision: Union[str, Sequence[str], None] = 'acebf2b5a5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualification_metadata', sa.Column('invalid_bid_clauses', sa.JSON(), nullable=True, comment='无效投标/否决投标条款'))
    op.add_column('qualification_metadata', sa.Column('project_annulment_clauses', sa.JSON(), nullable=True, comment='项目废标条款'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualification_metadata', 'project_annulment_clauses')
    op.drop_column('qualification_metadata', 'invalid_bid_clauses')
    # ### end Alembic commands ###
